#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

_SYS := $(shell uname 2>/dev/null || echo Unknown)
_SYS := $(patsubst MSYS%,MSYS,$(_SYS))
_SYS := $(patsubst MINGW%,MinGW,$(_SYS))

#
# SSBMaker
#
VERSION = 1.0.0
PACKAGE_NAME = SSBMaker
APP_NAME = SSBMaker
SSBMaker_APPLICATION_ICON = SSBMaker.png


#
# Resource files
#
SSBMaker_RESOURCE_FILES = \
Resources/SSBMaker.png
#
# Header files
#
SSBMaker_HEADER_FILES = \
Source/SSBWindow.h \
Source/AppDelegate.h \
Source/SSBFileManager.h \

#
# Class files
#
SSBMaker_OBJC_FILES = \
Source/main.m \
Source/SSBWindow.m \
Source/AppDelegate.m \
Source/SSBFileManager.m \

OBJC_FLAGS+= -DOBJC_RUNTIME_2_0

ifneq ($(filter $(_SYS),MSYS MinGW),)
OBJC_LIBS+= -ldispatch
endif

ifeq ($(_SYS),Linux)
OBJC_LIBS+= -ldispatch
endif

ifeq ($(_SYS),Darwin)
endif

ifeq ($(_SYS),FreeBSD)
endif

ifeq ($(_SYS),NetBSD)
endif

ifeq ($(_SYS),OpenBSD)
endif

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
